import { ScrollArea } from '@/components/ui/scroll-area';
import React from 'react';

const EULAComp = () => {
    return (
        <div>
            <ScrollArea className="max-h-96 overflow-y-auto">
                <div className='space-y-3'>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>1. License Grant</h1>
                        <p className='text-sm'>This software is licensed, not sold. Subject to the terms and conditions of this EULA, VoxGenie grants you a non-exclusive, non-transferable, limited license to use this software solely for personal, non-commercial purposes.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>2. Open-Source Nature</h1>
                        <p className='text-sm'>This software is released as open-source under the GPLv3 license. You are free to use, modify, and distribute the software in accordance with the terms of this license. However, the software and any derivative works are not to be sold or used for commercial purposes.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>3. Attribution</h1>
                        <p className='text-sm'>This project utilizes Coqui TTS as the base model for voice synthesis. Any use of this software must include proper attribution to the Coqui TTS project. For more information about Coqui TTS, please visit <a href='https://github.com/coqui-ai/TTS' target='_blank' rel='noopener noreferrer nofollow' className='underline hover:no-underline'>Coqui TTS website</a>.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>4. Restrictions</h1>
                        <p className='text-sm'>
                            <span className=''>You agree not to:</span>
                            <ul className='mt-1 ml-2 space-y-2'>
                                <li>(•) Sell, rent, lease, sublicense, or distribute this software for commercial gain.</li>
                                <li>(•) Use this software or any derivative works for any commercial purposes, including but not limited to, monetizing content generated by the software.</li>
                                <li>(•) Misrepresent the origin of the software or claim ownership of the software.</li>
                            </ul>
                        </p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>5. Ownership</h1>
                        <p className='text-sm'>All rights, titles, and interests in and to this software remain with VoxGenie. This EULA does not grant you any rights to the software's trademarks, logos, or other intellectual property.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>6. Disclaimer of Warranty</h1>
                        <p className='text-sm'>This software is provided "as-is," without any express or implied warranties. VoxGenie disclaims all warranties, including but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>7. Limitation of Liability</h1>
                        <p className='text-sm'>In no event shall VoxGenie be liable for any damages arising from the use or inability to use this software, including but not limited to, direct, indirect, incidental, or consequential damages.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>8. Termination</h1>
                        <p className='text-sm'>This license is effective until terminated. VoxGenie may terminate this license at any time if you violate any terms of this EULA. Upon termination, you must cease all use of the software and destroy any copies in your possession.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>9. Governing Law</h1>
                        <p className='text-sm'>This EULA shall be governed by and construed in accordance with the laws of INDIA.</p>
                    </div>
                    <div className='space-y-1'>
                        <h1 className='text-base font-bold'>10. Amendments</h1>
                        <p className='text-sm'>VoxGenie reserves the right to amend this EULA at any time. Any such amendments will be effective immediately upon posting on the project repository or distribution site.</p>
                    </div>
                </div>
            </ScrollArea>
        </div>
    );
};

export default EULAComp;